app_situation:
    resource: "@AppBundle/Resources/config/routing/situation.yml"
    prefix:   /situation

app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

app_visite:
    resource: "@AppBundle/Resources/config/routing/visite.yml"
    prefix:   /visite

app_point_vente:
    resource: "@AppBundle/Resources/config/routing/pointvente.yml"
    prefix:   /pointvente

app_etape:
    resource: "@AppBundle/Resources/config/routing/etape.yml"
    prefix:   /etape



poin_ventes:
    path:      /mobile/points/ventes
    defaults: { _controller: "AppBundle:Mobile:pointVentes" }
    methods:  GET

produits:
    path:      /mobile/produits
    defaults: { _controller: "AppBundle:Mobile:produits" }
    methods:  GET

create_point_ventes:
    path:      /mobile/create/points/ventes
    defaults: { _controller: "AppBundle:Mobile:createPointVentes" }
    methods:  [POST,GET]

create_visites:
    path:      /mobile/create/visites
    defaults: { _controller: "AppBundle:Mobile:createVisites" }
    methods:  POST

create_etatpes:
    path:      /mobile/create/etapes
    defaults: { _controller: "AppBundle:Mobile:createEtapes" }
    methods:  POST 

create_token:
    path:      /mobile/create/auth-token
    defaults: { _controller: "AppBundle:Mobile:postAuthTokens" }
    methods:  POST